// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import IndexpageviewerController from "./indexpageviewer_controller"
application.register("indexpageviewer", IndexpageviewerController)

import MapController from "./map_controller"
application.register("map", MapController)

import RouteController from "./route_controller"
application.register("route", RouteController)

import SharingController from "./sharing_controller"
application.register("sharing", SharingController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)
